[package]

name = "handlebars"
version = "0.12.0"
authors = ["Ning Sun <sunng@about.me>"]
description = "Handlebars templating implemented in Rust."
license = "MIT"
keywords = ["handlebars", "templating", "web"]
homepage = "https://github.com/sunng87/handlebars-rust"
repository = "https://github.com/sunng87/handlebars-rust"
documentation = "http://sunng.info/handlebars-rust/"
readme = "README.md"

[lib]

name = "handlebars"
path = "src/lib.rs"

[dependencies]

regex = "^0.1.41"
log = "^0.3.1"
rustc-serialize = { version = "^0.3.15", optional = true }
num = "^0.1.25"
lazy_static = "^0.1.14"
quick-error = "^0.1.3"
serde = { version = "^0.6.0", optional = true }
serde_json = { version = "^0.6.0", optional = true }

[features]
default = ["rustc-serialize"]
serde_type = ["serde", "serde_json"]

[dev-dependencies]
env_logger = "*"
maplit = "*"
#tojson_macros = "*"
serde_codegen = { "version" = "*", default-features = false }
serde_macros = "*"
#syntex = "*"
